name: deephit-env
channels:
  - sebp
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp
  - absl-py
  - aiohttp
  - aiosignal
  - aom
  - appnope
  - asttokens
  - async-timeout
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - blinker
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - captum
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - contourpy
  - cryptography
  - cycler
  - debugpy
  - decorator
  - ecos
  - entrypoints
  - easydict #
  - executing
  - expat
  - ffmpeg
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - frozenlist
  - future
  - gettext
  - gmp
  - gnutls
  - google-auth-oauthlib
  - grpc-cpp
  - grpcio
  - icu
  - idna
  - importlib-metadata
  - ipykernel
  - ipython
  - jedi
  - jpeg
  - jupyter_client
  - jupyter_core
  - kiwisolver
  - lame
  - lcms2
  - lerc
  - libabseil
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcxx
  - libdeflate
  - libffi
  - libgfortran
  - libgfortran5
  - libiconv
  - libidn2
  - liblapack
  - libopenblas
  - libosqp
  - libpng
  - libprotobuf
  - libqdldl
  - libsodium
  - libtasn1
  - libtiff
  - libunistring
  - libvpx
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - lifelines #
  - lightning #
  - llvm-openmp
  - markdown
  - markupsafe
  - matplotlib-base
  - matplotlib-inline
  - multidict
  - munkres
  - ncurses
  - nest-asyncio
  - nettle
  - ninja
  - numexpr
  - oauthlib
  - openh264
  - openjpeg
  - openssl
  - osqp
  - optuna #
  - p11-kit
  - packaging
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - prompt-toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pyasn1
  - pyasn1-modules
  - pycox #
  - pycparser
  - pygments
  - pyjwt
  - pyopenssl
  - pyparsing
  - pysocks
  - python=3.10.5
  - python-dateutil
  - python_abi
  - pytorch=1.12.1
  - pyu2f
  - pyyaml
  - pyzmq
  - qdldl-python
  - re2
  - readline
  - requests
  - requests-oauthlib
  - rsa
  - scikit-survival
  - scipy
  - setuptools
  - six
  - sleef
  - sqlite
  - stack_data
  - svt-av1
  - tensorboard-plugin-wit
  - tk
  - torchaudio
  - torchvision
  - tornado
  - torchtuples #
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - unicodedata2
  - urllib3
  - wcwidth
  - werkzeug
  - wheel
  - x264
  - x265
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - yaml
  - yarl
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - alembic==1.8.1
      - astor==0.8.1
      - autograd==1.4
      - autograd-gamma==0.5.0
      - autopage==0.5.1
      - brotli==1.0.9
      - cachetools==4.2.4
      - click==8.0.4
      - cliff==4.0.0
      - cloudpickle==2.2.0
      - cmaes==0.8.2
      - cmd2==2.4.2
      - colorlog==6.7.0
      - distlib==0.3.6
      - eli5==0.13.0
      - et-xmlfile==1.1.0
      - fastjsonschema==2.16.2
      - feather-format==0.4.1
      - filelock==3.8.0
      - fonttools==4.34.4
      - formulaic==0.4.0
      - fsspec==2022.7.1
      - google-auth==1.35.0
      - h5py==3.7.0
      - inflate64==0.3.0
      - interface-meta==1.3.0
      - ipython-genutils==0.2.0
      - jinja2==3.1.2
      - joblib==1.1.0
      - jsonschema==4.16.0
      - lifelines==0.27.1
      - llvmlite==0.39.0
      - mako==1.2.3
      - matplotlib==3.5.3
      - msgpack==1.0.4
      - multivolumefile==0.2.3
      - nbformat==5.7.3
      - numba==0.56.0
      - numpy==1.22.4
      - openpyxl==3.1.0
      - optuna==3.0.3
      - pandas==1.2.5
      - pbr==5.10.0
      - platformdirs==2.5.2
      - plotly==5.10.0
      - prettytable==3.4.1
      - protobuf==3.19.4
      - py7zr==0.20.0
      - pyarrow==9.0.0
      - pybcj==1.0.1
      - pycox==0.2.3
      - pycryptodomex==3.15.0
      - pydeprecate==0.3.2
      - pyperclip==1.8.2
      - pyppmd==0.18.3
      - pyrsistent==0.18.1
      - python-graphviz==0.20.1
      - pytorch-lightning==1.7.1
      - pytorch-lightning-bolts==0.3.2.post1
      - pytz==2022.2.1
      - pyzstd==0.15.3
      - ray==2.0.0
      - scikit-learn==1.1.2
      - seaborn==0.12.2
      - shap==0.41.0
      - sklearn-pandas==2.2.0
      - slicer==0.0.7
      - sqlalchemy==1.4.41
      - stevedore==4.0.1
      - tabulate==0.8.10
      - tenacity==8.1.0
      - tensorboard==2.10.0
      - tensorboard-data-server==0.6.1
      - tensorboardx==2.5.1
      - texttable==1.6.4
      - threadpoolctl==3.1.0
      - torchmetrics==0.9.3
      - torchtuples==0.2.2
      - virtualenv==20.16.5
      - wrapt==1.14.1
